### ISSUE TITLE
exception is thrown at startup wscat

### ISSUE THREAD

**Issue by gabrielmatau79** [pterodactyl/images#52]
Hi! i need help about thrown exception when execute :

 wscat -c "ws://localhost:8088/ari/events?api_key=asterisk:asterisk&app=hello-world" 

Ari Rest asterisk  thrown this

/usr/lib/node_modules/wscat/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/wscat/node_modules/ws/index.js:3:19)

please you can help me how to resolve this problem..!

**Comment by parkervcp** [comment]
What branch/image is this for? Why are you opening this on this repo at all?

**Comment by billiebongo** [comment]
hi i have the same issue on centos

**Comment by parkervcp** [comment]
This still gives me none of the informatimo I was looking for.
