### ISSUE TITLE
Missing library files in Java-11

### ISSUE THREAD

**Issue by addidotlol** [pterodactyl/images#80]
Panel Version: 1.4.2
Daemon Version: 1.4.4
Service: minecraft
Docker Image: quay.io/pterodactyl/core:java-11
Modified: no

Errors that you are experiencing:
The library libXrender.so.1 seems to be missing from the default installation of pterodactyl. This messes with some mods since the server will crash without it.

```
[20:49:19] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Brazier (brazier) encountered an error during the load_registries event phase
§7java.lang.UnsatisfiedLinkError: /usr/local/openjdk-11/lib/libawt_xawt.so: libXrender.so.1: cannot open shared object file: No such file or directory
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:196) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[server.jar:36.1] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [server.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [server.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [server.jar:?] {}
```

**Comment by nikrozman21** [comment]
Why would a headless server even need that library?
Have you tried starting it with nogui?

**Comment by addidotlol** [comment]
> 
> 
> Why would a headless server even need that library?
> Have you tried starting it with nogui?

I tried starting it with nogui but it didn't change the result.

**Comment by addidotlol** [comment]
The issue seems to have resolved itself after restarting the whole machine. Not sure how that fixed it but it worked. Sorry for wasting any time.
